server:
  port: 8888
spring:
  application:
    name: SharedBike
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sharedbike?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

